### PR TITLE
Add Carousel template

### PR DESCRIPTION
**Pull request by krimmelworks**
Add template with carousel hard-coded. Still dependent on plugin

### CODE REVIEW

**Comment by smudireddy22** [comment]
PR moved to production.
Stephanie, can you validate your changes

**Comment by krimmelworks** [comment]
Not working quite right. I will push a new version

**Comment by smudireddy22** [comment]
Ok
Let me know once your PR is ready

**Comment by krimmelworks** [comment]
ready now, thanks!
—

Stephanie Krimmel
***@***.***
206-422-8957

**Comment by smudireddy22** [comment]
Done.

**Pull request merged**
